site_name: Lynx's Blog
theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - abbr #缩写或名词
  - pymdownx.snippets:  #片段，将任意文件或部分内容嵌入到文档中  
  - admonition:  #警告或标注
  - pymdownx.details:  #细节折叠
  - pymdownx.superfences:  #超级围栏
  - attr_list:   #属性列表（按钮-颜色图标）
  - def_list:   #定义列表
  - footnotes:  #行内脚注
  - meta:   #元数据
  - md_in_html:  #HTML 中的 Markdown
  - toc:  #目录
      toc_depth: 3 #目录深度，默认6，0则隐藏
#      title: On this page  #默认值，自动获取
#      permalink: true   #每个标题的末尾添加段落符号锚链接，默认false
#      permalink: ⚓︎  #每个标题的末尾添加自定义符号锚链接
#      permalink_title: Anchor link to this section for reference #在悬停时显示并由屏幕阅读器阅读的锚链接的标题
  - tables #表格（未推荐）
  - pymdownx.arithmatex:  #数学公式
      generic: true  
  - pymdownx.betterem:   #粗体斜体
      smart_enable: all
  - pymdownx.caret:  #插入角标符号(`^`)
  - pymdownx.mark:  #双等号(`==`)
  - pymdownx.tilde:  #波浪号(`~`)
  - pymdownx.critic:  #评论家(突出显示建议更改)，未推荐
#      mode: reject #应如何解析标记，默认view查看更改，accept是接受更改，reject是拒绝更改
  - pymdownx.keys:   #键盘键和组合  
  - pymdownx.emoji:  #表情符号
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
#      options: #默认无
#        custom_icons: #允许列出要在 Markdown 中使用的附加图标集的文件夹
#          - overrides/.icons
  - pymdownx.highlight:  #代码高亮，对代码块（SuperFences）和行内代码块（InlineHilite）的语法突出显示
  - pymdownx.inlinehilite:  #行内高亮
  - pymdownx.smartsymbols:  #智能符号
  - pymdownx.tabbed:  #内容选项卡
      alternate_style: true  #启用内容选项卡替代样式，必须开启
  - pymdownx.tasklist:  #任务列表
      custom_checkbox: true   #切换复选框的呈现样式，将原生复选框样式替换为漂亮的图标
#      clickable_checkbox: true  #切换复选框是否可点击，默认false，不建议开
  - search:
  - mermaid2:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    

extra_javascript:
  - https://cdn.jsdelivr.net/npm/baidu-tongji@0.0.1/index.min.js  #百度统计
  - javascripts/mathjax.js  #数学公式的JS
  - https://lib.baomitu.com/babel-polyfill/7.12.1/polyfill.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
