name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
      - run: pip install mkdocs-material
      - run: pip install mkdocs-mermaid2-plugin
      - run: pip install mknotebooks
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-git-revision-date-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugi
      - run: mkdocs gh-deploy --force
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



